import { z } from 'zod';

export const remediatedResourceSchema = z.object({
  type: z.string().optional(),
  name: z.string().min(1),
  role: z.enum(['primary', 'satellite']).optional(),
});

export type RemediatedResource = z.infer<typeof remediatedResourceSchema>;

export const draftPrRequestSchema = z.object({
  resourceId: z.string().min(1),
  resourceName: z.string().min(1),
  resourceAliases: z.array(z.string().min(1)).optional(),
  actionType: z.string().min(1),
  branchName: z.string().min(1),
  commitMessage: z.string().min(1),
  hclDiff: z.string(),
  monthlySavingsUsd: z.number(),
  remediatedResources: z.array(remediatedResourceSchema).optional(),
});

export type DraftPrRequest = z.infer<typeof draftPrRequestSchema>;

export type DraftPrResponse = {
  success: true;
  simulated: boolean;
  prNumber: number;
  prUrl: string;
};

export function remediationPrTitle(commitMessage: string): string {
  return commitMessage.split(/\r?\n/, 1)[0].trim();
}

export function isGitFlowDemoMode(options: {
  githubToken?: string;
  demoMode?: string;
  isEvaluator?: boolean;
}): boolean {
  if (options.demoMode === 'true') {
    return true;
  }

  if (!options.githubToken) {
    return true;
  }

  return options.isEvaluator !== true;
}

export function listRemediatedResources(
  input: Pick<DraftPrRequest, 'resourceId' | 'resourceName' | 'hclDiff' | 'remediatedResources'>,
): RemediatedResource[] {
  if (input.remediatedResources && input.remediatedResources.length > 0) {
    return input.remediatedResources;
  }

  const fromDiff = parseRemediatedResourcesFromDiff(input.hclDiff);
  if (fromDiff.length > 0) {
    return fromDiff.map((resource, index) => ({
      ...resource,
      role: index === 0 ? 'primary' : 'satellite',
    }));
  }

  return [
    {
      name: input.resourceName,
      role: 'primary',
    },
  ];
}

export function buildRemediationPrBody(input: DraftPrRequest): string {
  const remediatedList = listRemediatedResources(input)
    .map((resource) => formatRemediatedResourceLine(resource, input.resourceId))
    .join('\n');

  return `## ⚡ CloudPulse FinOps Remediation Proposal

- **Target Resource:** \`${input.resourceName}\` (\`${input.resourceId}\`)
- **Action:** \`${input.actionType}\`
- **Estimated Monthly Savings:** \`+$${input.monthlySavingsUsd.toFixed(2)}/mo\`

### Remediated Resources
${remediatedList}

### Terraform Plan Preview
\`\`\`hcl
${input.hclDiff}
\`\`\`

*Automated proposal generated by PulseAdvisor.`;
}

export function updateConsolidatedPrBody(
  existingBody: string,
  newInput: DraftPrRequest,
): string {
  if (existingBody.includes(newInput.resourceId)) {
    return existingBody;
  }

  const savingsMatch = existingBody.match(/\+\$([\d.]+)\/mo/);
  const currentSavings = savingsMatch ? parseFloat(savingsMatch[1]) : 0;
  const newTotalSavings = currentSavings + newInput.monthlySavingsUsd;

  const resName = newInput.resourceName;
  const resId = newInput.resourceId;
  const BT = String.fromCharCode(96);
  const newResourceLine = `- **Target Resource:** ${BT}${resName}${BT} (${BT}${resId}${BT})`;
  const addressName = newInput.resourceName.replace(/[^a-zA-Z0-9_]/g, '_');
  const newRemediatedLine = `- ${BT}aws_ebs_volume.${addressName}${BT} (primary) — ${BT}${resId}${BT}`;

  let updated = existingBody;

  if (savingsMatch) {
    updated = updated.replace(
      savingsMatch[0],
      `+$${newTotalSavings.toFixed(2)}/mo`,
    );
  }

  if (updated.includes('- **Target Resource:**')) {
    updated = updated.replace(
      '- **Target Resource:**',
      `${newResourceLine}\n- **Target Resource:**`,
    );
  }

  if (updated.includes('### Terraform Plan Preview')) {
    updated = updated.replace(
      '### Terraform Plan Preview',
      `${newRemediatedLine}\n\n### Terraform Plan Preview`,
    );
  }

  if (updated.includes('```hcl')) {
    updated = updated.replace(
      '```hcl',
      `\`\`\`hcl\n${newInput.hclDiff}`,
    );
  }

  return updated;
}

export function updateConsolidatedPrTitle(
  existingTitle: string,
  newInput: DraftPrRequest,
): string {
  if (existingTitle.includes(newInput.resourceName) || existingTitle.includes(newInput.resourceId)) {
    return existingTitle;
  }
  return `${existingTitle.trim()}, ${newInput.resourceName}`;
}

function parseRemediatedResourcesFromDiff(hclDiff: string): RemediatedResource[] {
  const headerRe = /resource\s+"([^"]+)"\s+"([^"]+)"/g;
  const seen = new Set<string>();
  const resources: RemediatedResource[] = [];
  let match = headerRe.exec(hclDiff);

  while (match) {
    const key = `${match[1]}.${match[2]}`;
    if (!seen.has(key)) {
      seen.add(key);
      resources.push({ type: match[1], name: match[2] });
    }
    match = headerRe.exec(hclDiff);
  }

  return resources;
}

function formatRemediatedResourceLine(
  resource: RemediatedResource,
  fallbackResourceId: string,
): string {
  const address = resource.type ? `${resource.type}.${resource.name}` : resource.name;
  const roleLabel =
    resource.role === 'satellite'
      ? 'coupled satellite'
      : resource.role === 'primary'
        ? 'primary'
        : undefined;
  const suffix = roleLabel ? ` (${roleLabel})` : '';

  if (resource.role === 'primary') {
    return `- \`${address}\`${suffix} — \`${fallbackResourceId}\``;
  }

  return `- \`${address}\`${suffix}`;
}

export function sanitizeBranchName(branchName: string): string {
  const cleaned = branchName
    .trim()
    .replace(/\s+/g, '-')
    .replace(/[^a-zA-Z0-9._\-/]/g, '-')
    .replace(/\.\.+/g, '.')
    .replace(/\/+/g, '/')
    .replace(/^[-/]+|[-/]+$/g, '');

  return cleaned.length > 0 ? cleaned : 'finops/remediation';
}
