import { z } from 'zod';

export const remediatedResourceSchema = z.object({
  type: z.string().optional(),
  name: z.string().min(1),
  role: z.enum(['primary', 'satellite']).optional(),
});

export type RemediatedResource = z.infer<typeof remediatedResourceSchema>;

export const draftPrRequestSchema = z.object({
  resourceId: z.string().min(1),
  resourceName: z.string().min(1),
  actionType: z.string().min(1),
  branchName: z.string().min(1),
  commitMessage: z.string().min(1),
  hclDiff: z.string(),
  monthlySavingsUsd: z.number(),
  remediatedResources: z.array(remediatedResourceSchema).optional(),
});

export type DraftPrRequest = z.infer<typeof draftPrRequestSchema>;

export type DraftPrResponse = {
  success: true;
  simulated: boolean;
  prNumber: number;
  prUrl: string;
};

export function isGitFlowDemoMode(options: {
  githubToken?: string;
  demoMode?: string;
  auditorMode?: 'SIMULATED' | 'LIVE';
}): boolean {
  if (options.demoMode === 'true') {
    return true;
  }

  if (!options.githubToken) {
    return true;
  }

  return options.auditorMode !== 'LIVE';
}

export function listRemediatedResources(
  input: Pick<DraftPrRequest, 'resourceId' | 'resourceName' | 'hclDiff' | 'remediatedResources'>,
): RemediatedResource[] {
  if (input.remediatedResources && input.remediatedResources.length > 0) {
    return input.remediatedResources;
  }

  const fromDiff = parseRemediatedResourcesFromDiff(input.hclDiff);
  if (fromDiff.length > 0) {
    return fromDiff.map((resource, index) => ({
      ...resource,
      role: index === 0 ? 'primary' : 'satellite',
    }));
  }

  return [
    {
      name: input.resourceName,
      role: 'primary',
    },
  ];
}

export function buildRemediationPrBody(input: DraftPrRequest): string {
  const remediatedList = listRemediatedResources(input)
    .map((resource) => formatRemediatedResourceLine(resource, input.resourceId))
    .join('\n');

  return `## ⚡ CloudPulse FinOps Remediation Proposal

- **Target Resource:** \`${input.resourceName}\` (\`${input.resourceId}\`)
- **Action:** \`${input.actionType}\`
- **Estimated Monthly Savings:** \`+$${input.monthlySavingsUsd.toFixed(2)}/mo\`

### Remediated Resources
${remediatedList}

### Terraform Plan Preview
\`\`\`hcl
${input.hclDiff}
\`\`\`

*Automated proposal generated by PulseAdvisor.*`;
}

function parseRemediatedResourcesFromDiff(hclDiff: string): RemediatedResource[] {
  const headerRe = /resource\s+"([^"]+)"\s+"([^"]+)"/g;
  const seen = new Set<string>();
  const resources: RemediatedResource[] = [];
  let match = headerRe.exec(hclDiff);

  while (match) {
    const key = `${match[1]}.${match[2]}`;
    if (!seen.has(key)) {
      seen.add(key);
      resources.push({ type: match[1], name: match[2] });
    }
    match = headerRe.exec(hclDiff);
  }

  return resources;
}

function formatRemediatedResourceLine(
  resource: RemediatedResource,
  fallbackResourceId: string,
): string {
  const address = resource.type ? `${resource.type}.${resource.name}` : resource.name;
  const roleLabel =
    resource.role === 'satellite'
      ? 'coupled satellite'
      : resource.role === 'primary'
        ? 'primary'
        : undefined;
  const suffix = roleLabel ? ` (${roleLabel})` : '';

  if (resource.role === 'primary') {
    return `- \`${address}\`${suffix} — \`${fallbackResourceId}\``;
  }

  return `- \`${address}\`${suffix}`;
}

export function sanitizeBranchName(branchName: string): string {
  const cleaned = branchName
    .trim()
    .replace(/\s+/g, '-')
    .replace(/[^a-zA-Z0-9._\-/]/g, '-')
    .replace(/\.\.+/g, '.')
    .replace(/\/+/g, '/')
    .replace(/^[-/]+|[-/]+$/g, '');

  return cleaned.length > 0 ? cleaned : 'finops/remediation';
}
