import { z } from 'zod';

export const draftPrRequestSchema = z.object({
  resourceId: z.string().min(1),
  resourceName: z.string().min(1),
  actionType: z.string().min(1),
  branchName: z.string().min(1),
  commitMessage: z.string().min(1),
  hclDiff: z.string(),
  monthlySavingsUsd: z.number(),
});

export type DraftPrRequest = z.infer<typeof draftPrRequestSchema>;

export type DraftPrResponse = {
  success: true;
  simulated: boolean;
  prNumber: number;
  prUrl: string;
};

export const SIMULATED_DRAFT_PR: DraftPrResponse = {
  success: true,
  simulated: true,
  prNumber: 104,
  prUrl: 'https://github.com/example/cloudpulse/pull/104',
};

export function isGitFlowDemoMode(
  env: Record<string, string | undefined>,
): boolean {
  return !env['GITHUB_TOKEN'] || env['DEMO_MODE'] === 'true';
}

export function buildRemediationPrBody(input: DraftPrRequest): string {
  return `## ⚡ CloudPulse FinOps Remediation Proposal

- **Target Resource:** \`${input.resourceName}\` (\`${input.resourceId}\`)
- **Action:** \`${input.actionType}\`
- **Estimated Monthly Savings:** \`+$${input.monthlySavingsUsd.toFixed(2)}/mo\`

### Terraform Plan Preview
\`\`\`hcl
${input.hclDiff}
\`\`\`

*Automated proposal generated by PulseAdvisor.*`;
}

export function sanitizeBranchName(branchName: string): string {
  const cleaned = branchName
    .trim()
    .replace(/\s+/g, '-')
    .replace(/[^a-zA-Z0-9._\-/]/g, '-')
    .replace(/\.\.+/g, '.')
    .replace(/\/+/g, '/')
    .replace(/^[-/]+|[-/]+$/g, '');

  return cleaned.length > 0 ? cleaned : 'finops/remediation';
}
